# Inputs. Defaults are the smallest workable sizes (FR-012 — single-AZ demo, teardown-friendly).

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "project" {
  type    = string
  default = "wb-health-monitor"
}

variable "vpc_cidr" {
  type    = string
  default = "10.20.0.0/16"
}

# API image tag to deploy — CI passes the git SHA; the default lets a first apply stand up the infra
# before the image exists (the API service sits unhealthy until the first push, which is fine). The
# dashboard is a static export (no image) — it is `aws s3 sync`ed by CI, not tagged here.
variable "api_image_tag" {
  type    = string
  default = "bootstrap"
}

variable "db_name" {
  type    = string
  default = "wbhealth"
}

variable "db_username" {
  type    = string
  default = "wbhealth"
}

# The DB password + the Anthropic key are NOT variables with values — they live in Secrets Manager
# (FR-007). The password is generated by Terraform (random_password) and stored there; the Anthropic
# key is put into its secret out-of-band (README) so it never touches state in plaintext form.

variable "db_instance_class" {
  type    = string
  default = "db.t4g.micro"
}

variable "db_allocated_storage" {
  type    = number
  default = 20
}

variable "api_cpu" {
  type    = number
  default = 256
}

variable "api_memory" {
  type    = number
  default = 512
}

# --- Custom domains (FR-015). All optional — unset ⇒ the default CloudFront/ALB hostnames. ---
#
# route53_zone_name is the EXISTING hosted zone Terraform looks up (e.g. "example.com"); the domain
# must already be registered + delegated to Route53 (a manual step — see docs/DEPLOYMENT.md). When a
# zone name is set, `domain_name` gives the app its URL (CloudFront) and `api_domain_name` optionally
# gives the API its own subdomain (ALB HTTPS).
variable "route53_zone_name" {
  type    = string
  default = ""
}

variable "domain_name" {
  type    = string
  default = "" # e.g. "app.example.com" — the dashboard URL
}

variable "api_domain_name" {
  type    = string
  default = "" # e.g. "api.example.com" — a dedicated API subdomain (optional; same-origin works too)
}

# Cron for the batch pipeline (ingest → dbt-build → train). Default: daily 06:00 UTC (FR-005).
variable "pipeline_schedule" {
  type    = string
  default = "cron(0 6 * * ? *)"
}

# GitHub repo "owner/name" — scopes the OIDC deploy role's trust to this repo only (FR-010).
variable "github_repo" {
  type    = string
  default = "sunilmogadati/wb-health-monitor"
}
