# Inputs. Defaults are the smallest workable sizes (FR-012 — single-AZ demo, teardown-friendly).

variable "region" {
  type    = string
  default = "us-east-1"
}

variable "project" {
  type    = string
  default = "wb-health-monitor"
}

variable "vpc_cidr" {
  type    = string
  default = "10.20.0.0/16"
}

# Container image tags to deploy — CI passes the git SHA; defaults let a first apply stand up the
# infra before images exist (services will sit unhealthy until the first push, which is fine).
variable "api_image_tag" {
  type    = string
  default = "bootstrap"
}

variable "web_image_tag" {
  type    = string
  default = "bootstrap"
}

variable "db_name" {
  type    = string
  default = "wbhealth"
}

variable "db_username" {
  type    = string
  default = "wbhealth"
}

# The DB password + the Anthropic key are NOT variables with values — they live in Secrets Manager
# (FR-007). The password is generated by Terraform (random_password) and stored there; the Anthropic
# key is put into its secret out-of-band (README) so it never touches state in plaintext form.

variable "db_instance_class" {
  type    = string
  default = "db.t4g.micro"
}

variable "db_allocated_storage" {
  type    = number
  default = 20
}

variable "api_cpu" {
  type    = number
  default = 256
}

variable "api_memory" {
  type    = number
  default = 512
}

variable "web_cpu" {
  type    = number
  default = 256
}

variable "web_memory" {
  type    = number
  default = 512
}

# Optional ACM certificate ARN. When set, the ALB serves HTTPS:443 and redirects 80→443 (FR-001/SC-001).
# When empty (the demo default), the ALB serves plain HTTP:80 on its AWS hostname — deployable with no
# domain. Custom domain + cert is the documented stretch.
variable "acm_certificate_arn" {
  type    = string
  default = ""
}

# Cron for the batch pipeline (ingest → dbt-build → train). Default: daily 06:00 UTC (FR-005).
variable "pipeline_schedule" {
  type    = string
  default = "cron(0 6 * * ? *)"
}

# GitHub repo "owner/name" — scopes the OIDC deploy role's trust to this repo only (FR-010).
variable "github_repo" {
  type    = string
  default = "sunilmogadati/wb-health-monitor"
}
